### ISSUE TITLE
clone 值时， file 对象会丢失

### ISSUE THREAD

**Issue by HydrogenPan19** [FEMessage/el-form-renderer#106]
## Describe the bug
使用自定义组件时，若model 值包含 File 对象，会丢失

我的用例，封装了 el-upload 组件，需要拿到 file 对象，
结果经过 `getFormValue` 的 `clone`  值后， file 对象丢失了

## Screenshots
```
这个是 `getFormValue` 得到的值
{
  "status": "ready",
  "name": "idea-settings-190507 - 副本.bin",
  "size": 12047,
  "percentage": 0,
  "uid": 1569289372447,
  "raw": {
    "uid": 1569289372447
  }
}
```

raw 是 File 的原始对象，结果只剩 element-ui 赋的 uid 字段了。。

## Expected behavior
正常返回 file 对象

## environment information
 - v1.11.2

**Comment by levy9527** [comment]
收到！

**Comment by levy9527** [comment]
你好，最新版本解决这个问题了。

**Comment by HydrogenPan19** [comment]
非常感谢，响应很及时。

**Comment by HydrogenPan19** [comment]
题外话，希望没有同学对自定义组件返回的 object 直接修改了。。
