### ISSUE TITLE
支持 v-model

### ISSUE THREAD

**Issue by donaldshen** [FEMessage/el-form-renderer#149]
**Is your feature request related to a problem? Please describe.**
且不说 updateForm & getFormValue 的繁琐；
常见的场景是 el-dialog 里套一个 el-form-renderer。如果希望 form 有默认值，那当前的做法是：
1. elDialog.visible = true，然后**两**层 nextTick 后调用 updateForm（一层不保险，有反馈过
2. 监听 el-dialog 的 opened 事件，然后 updateForm

两种都很丑。且易触发 rule 校验等各种奇怪问题
![image](https://user-images.githubusercontent.com/19591950/71243504-732bef80-234b-11ea-80ba-b9edaf4267c2.png)

**Describe the solution you'd like**
v-model，别让用户关心 updateForm 和 getFormValue 的时机

**Comment by daiyang123456** [comment]
对，如果使用updateForm更新数据，似乎不符合双向绑定的思想。

**Comment by dream2023** [comment]
对，这个功能好，需要赶紧实现，全国人民翘首以盼

**Comment by levy9527** [comment]
> 全国人民翘首以盼

呼声这么大吗🤣
