### ISSUE TITLE
[bug]: 独立设置的 `disabled` 失效

### ISSUE THREAD

**Issue by eviIIt** [FEMessage/el-form-renderer#158]
## Describe the bug

如题

### 1

![image](https://user-images.githubusercontent.com/53422750/73826171-461e9800-4838-11ea-8403-87f6e4867484.png)

### 2

![image](https://user-images.githubusercontent.com/53422750/73826224-6189a300-4838-11ea-8d2a-0f9273cdd843.png)

![image](https://user-images.githubusercontent.com/53422750/73826237-68b0b100-4838-11ea-911f-134090da1a6c.png)

## Expected behavior

- 期待回复生效
- 影响到项目, 但曲线办法是部门开始使用 `readonly`;

## environment information
 - Version 1.13.1
 - OS: macOS
 - Browser: ever-green

**Comment by donaldshen** [comment]
其实没失效，是示例错了。
### 示例的问题
#### disabled 应该写在和 el 平级的位置
```js
{
  disabled: true,
  el: {},
}
```

#### content 不是响应式的，`$set(content)` 没用
内部用的是 innerContent，content 在 created 时用一次就无视了

### 解决方案
1. 正确放置 disabled
2. content 在 v-model 的 pr 中已变成响应式，等待后续发版吧。但 disabled 依然要放在 el 平级处哦
