### ISSUE TITLE
content 表单下的 disabled 失效

### ISSUE THREAD

**Issue by DeepenLau** [FEMessage/el-form-renderer#166]
## Describe the bug
content 表单下数组里面传入的 disabled 失效
传入的 disabled 为 true
![image](https://user-images.githubusercontent.com/14030995/75016172-589a0200-54c5-11ea-8300-fa1f37e721ed.png)

## Screenshots
![image](https://user-images.githubusercontent.com/14030995/75015901-b843dd80-54c4-11ea-8ba0-bd21322c8a63.png)
<br>
![image](https://user-images.githubusercontent.com/14030995/75015913-bc6ffb00-54c4-11ea-91c5-33d39874d185.png)

**Comment by donaldshen** [comment]
same as https://github.com/FEMessage/el-form-renderer/issues/158#issuecomment-588017593

这种写法我重新兼容一下吧，稍候提个 pr

**Comment by DeepenLau** [comment]
1.是不是说升级了新版本之后，还要自己手改？
2.那项目中所有用到这个组件的，升级后都要自己手改吗？

**Comment by DeepenLau** [comment]
> same as [#158 (comment)](https://github.com/FEMessage/el-form-renderer/issues/158#issuecomment-588017593)
> 
> 这种写法我重新兼容一下吧，稍候提个 pr

好的，能兼容最好，谢谢
