### ISSUE TITLE
type=checkbox-group的时候，options支持value属性

### ISSUE THREAD

**Issue by JE-lee** [FEMessage/el-form-renderer#170]
我注意到最近的更新，radio-group的options已经支持{ label, value }选项，现在希望checkbox-group的选项也支持{label, value}选项，将label和value分开。

![image](https://user-images.githubusercontent.com/19794813/75230845-5ef2eb80-57ef-11ea-84fa-2ac5f959f7ae.png)

感谢。

**Comment by donaldshen** [comment]
https://element.eleme.cn/#/zh-CN/component/checkbox#checkbox-attributes

checkbox 原生是不支持的……

可以考虑，你可以先用 inputFormat & outputFormat 顶一下
```js
{
  type: "checkbox",
  id: "id",
  default: 1,
  options: [{ label: "a" }, { label: "b" }],
  inputFormat: form => ({'1': 'a', '2': 'b'}[form.id]),
  outputFormat: v => ({ a: 1, b: 2 }[v]),
}
```

**Comment by JE-lee** [comment]
> https://element.eleme.cn/#/zh-CN/component/checkbox#checkbox-attributes
> 
> checkbox 原生是不支持的……
> 
> 可以考虑，你可以先用 inputFormat & outputFormat 顶一下
> 
> ```js
> {
>   type: "checkbox",
>   id: "id",
>   default: 1,
>   options: [{ label: "a" }, { label: "b" }],
>   inputFormat: form => ({'1': 'a', '2': 'b'}[form.id]),
>   outputFormat: v => ({ a: 1, b: 2 }[v]),
> }
> ```
