### ISSUE TITLE
新特性：v-model 不应该清掉初始值中不存在于 content 中的项

### ISSUE THREAD

**Issue by donaldshen** [FEMessage/el-form-renderer#179]
当使用 slot 的时候，我们希望 slot 中的值也出现在 v-model 中，这样提交表单时直接提交整个 model 即可

**Comment by Star945** [comment]
v-model这个东西某些场景下是真的不好用……我已经放弃使用他了 尤其自定义组件感觉会造成循环渲染

**Comment by levy9527** [comment]
😂 正在找人接手中...

**Comment by snowlocked** [comment]
slot内部的组件值可以通过遍历读取出来，但是监听slot内部内容就不太合适且具有难度，毕竟这些slot本身的逻辑就应由使用者自己管理。使用本组件时，应当避免和减少使用slot来处理。一般情况下可以传入自定义component来满足需求。组件插手管理这个slot里的value值有些画蛇添足，甚至有可能被用户当成el-form使用，失去了原有组件的作用了。

**Comment by levy9527** [comment]
如果此特性只是因为slot这个场景的话，暂不考虑。如后面有新的场景，可以重新打开此issue
