### ISSUE TITLE
Support inline form items?

### ISSUE THREAD

**Issue by michaelbukachi** [FEMessage/el-form-renderer#181]
**Is your feature request related to a problem? Please describe.**
Hello, is it possible to do inline forms using this library? Or inline specific form items?

**Describe the solution you'd like**
Add support for inline form items.

**Comment by levy9527** [comment]
yeah, under consideration

**Comment by snowlocked** [comment]
it supports some props of el-form, you can try this to set inline form items
```html
<el-form-renderer inline :content="content"></el-form-renderer>
```
