### ISSUE TITLE
updateValue do not call inputFormatter Default

### ISSUE THREAD

**Issue by lianghx-319** [FEMessage/el-form-renderer#19]
## Version
1.3.0

## OS/Browsers version
Windows 10 - Chrome 73

## Framework
nuxt

## Questions
my formContent item has set inputFormat, there is nothing wrong when call updateForm. But when i call updateVaule which setted inputFormat, error occurred.
![updateForm](https://user-images.githubusercontent.com/27187946/54805911-70647700-4cb3-11e9-8616-18dd30045495.png)
Here will call the inpueFormat inside!
![image](https://user-images.githubusercontent.com/27187946/54805963-9db12500-4cb3-11e9-9b93-8de1c4554430.png)
But updateVaule didn't.

## What is Expected?
Maybe write the default inputFormat code in the function updateValue, because updateForm just calls updateValue Iteratively

**Comment by levy9527** [comment]
Please use updateForm, [updateValue  is deprecated](https://github.com/FEMessage/el-form-renderer/releases/tag/v1.3.0).
