### ISSUE TITLE
type=checkbox 点击 label 后，不会触发 change 事件

### ISSUE THREAD

**Issue by Jogiter** [FEMessage/el-form-renderer#196]
```js
{
  type: "checkbox",
  id: "id",
  label: 'checkbox'
}
```

1. label 和 checkbox 的顺序是反的。正确的应该是 checkbox label。使用组件渲染出来的是 label checkbox
2. 最终渲染出来的 checkbox，点击 label 后，不会触发 change 事件修改 checkbox 的值

**Comment by levy9527** [comment]
牛逼，说得这么抽象也能看得懂 @snowlocked

**Comment by levy9527** [comment]
请问，到底是什么场景呢。你说的有道理，但我们无法找到你的场景，因而代码不能简单地就去改动

**Comment by Jogiter** [comment]
![Dingtalk_20200924175214](https://user-images.githubusercontent.com/9711036/94130281-0a037a80-fe8f-11ea-9345-16c85effd92c.jpg)

如图。在查询表格的时，选择特殊的状态一起查询。这时需要用单独的 checkbox 来渲染（期望 data 输出 boolean）。

```js
// expected
{
  id: 'isNewToday',
  type: 'checkbox',
  default: false,
  label: 'mycheckbox'
},
```

当然。可以用 checkbox-group 实现。

```js
{
  id: 'isNewToday',
  type: 'checkbox-group',
  default: [],
  options: [
    {
      label: '今日新增',
    }
  ]
},
```

此时 isNewToday 的值是 ['今日新增'] 或者 []。而期望的是 boolean

**Comment by snowlocked** [comment]
这个可以使用 `inputFormat` 和 `outputFormat` 将数组转换一下
