### ISSUE TITLE
disabled 的时候链接可否跳转

### ISSUE THREAD

**Issue by MiffyCooper** [FEMessage/el-form-renderer#2]
使用场景如下：
 disabled的时候 点击可以跳转 edit的时候可以编辑
![image](https://user-images.githubusercontent.com/20179564/50432469-e2276180-090c-11e9-952c-48d38980cfd3.png)
![image](https://user-images.githubusercontent.com/20179564/50432474-f3706e00-090c-11e9-9532-3b45b7c6ebef.png)

**Comment by levy9527** [comment]
在规划中。需要全面升级

**Comment by donaldshen** [comment]
这个用 slot 自行控制渲染内容吧
