### ISSUE TITLE
回填时，保留model的数据

### ISSUE THREAD

**Issue by yolofit** [FEMessage/el-form-renderer#210]
**Describe the solution you'd like**
数据回填时，model经transformOutputValue处理之后，只保留content内的id作为form的属性

### 期望
其他字段也保留

### 场景：

form表单的其他字段，可能会在其他的地方使用，如下代码。
实际上model经transformOutputValue处理之后已丢失了。

[在线demo](https://codesandbox.io/s/elated-shtern-86ywq?file=/src/App.vue)

```
this.form = {
    name: 'tom',
    age: 8
}
<el-form-renderer v-model="form" :content="[{id: 'name', label:'姓名'}]" > 
<template>
{{form.age}}  改变form.name,会导致form.age变成undefined
</template>
</el-form-renderer>
```

**Comment by levy9527** [comment]
那个函数你也看过，可以动手改一下，先试用下效果😄。主要这里不知道会对用户造成什么样的影响，故谨慎。

**Comment by levy9527** [comment]
现在最新版本，直接使用 updateForm 的话，冗余字段是会保留的。
