### ISSUE TITLE
增加请求参数配置

### ISSUE THREAD

**Issue by sogud** [FEMessage/el-form-renderer#222]
**如果我想做一个联动的select组件 A、B。B请求函数依赖A的value，如何去做？**

目前我是通过props传入一个map参数合集，对应id字段，如果参数合集更新则重新调用接口，根据change事件手动更新参数，如果在复杂一点则用了slot代替了content里的组件，如何有更好的做法？

**Comment by levy9527** [comment]
你意思是，做两个组件，还是一个组件？

如果A/B组成一个select组件，那就封装成个一个自定义组件，实现v-model，再使用 compoenent 属性接入即可，再复杂的逻辑，也能接入进来。可查看[文档](https://github.com/FEMessage/el-form-renderer/blob/dev/docs/guide-custom-component.md)

如果是两个组件，那就是通过 on 事件去联动了。https://femessage.github.io/el-form-renderer/#/Demo/on

**Comment by levy9527** [comment]
当然，你可以可以利用好 outpurFormat，把多个组件、复杂逻辑全部做成一个组件，通过 outputFormat 输出值，只是这样维护起来可能不太直观。

也即 form 的 content 定义为：
```
{
  id: '不存在的接口字段',
  component: '复杂的组件',
  outputFormat: value => {
    '接口字段1': value.key1,
    '接口字段2': value.key2,
  }
}

```

**Comment by levy9527** [comment]
如仍有疑问，可以进群讨论：https://github.com/FEMessage/el-data-table/issues/181
