### ISSUE TITLE
el-cascader 级联组件的异步设值支持

### ISSUE THREAD

**Issue by cjfff** [FEMessage/el-form-renderer#23]
## Version
1.3.0

## OS/Browsers version
Windows 10 - Chrome 73

## Framework
nuxt

## Questions
I want to use the el-cascader in my project, but  my props options is asynchronous, now i not found the api in the document
![image](https://user-images.githubusercontent.com/20502762/55553168-11bae680-5712-11e9-9671-92e3c4914290.png)

## What is Expected?
Get asynchronous support of props data

**Comment by FlySnails** [comment]
默认没得cascader ，用slot自己加吧

**Comment by 2nthony** [comment]
> 默认没得cascader ，用slot自己加吧

目前来说, [slot](https://github.com/FEMessage/el-form-renderer#slot) 是个不错的替代方案

`$type` 其实可以是所有已经注册的以`el-`开头的组件 = `el-${$type}`

**Comment by levy9527** [comment]
你可以这样做：
1. 初如化el-form-renderer 的 content: []
2. 调用接口，获得数据
3. 重新设置el-form-renderer的 content，把获得的数据放进去

**Comment by FlySnails** [comment]
> 你可以这样做：
> 
> 1. 初如化el-form-renderer 的 content: []
> 2. 调用接口，获得数据
> 3. 重新设置el-form-renderer的 content，把获得的数据放进去

除了slot，像这样动态set进去也是可行的
this.content.forEach(v => { if(v.$id === ${id}) this.$set(v.$el, 'options', ${options})});

**Comment by cjfff** [comment]
已通过插槽`<slot />`解决此问题
