### ISSUE TITLE
feature:期待能够支持elementUI穿梭框组件的动态设值

### ISSUE THREAD

**Issue by Barretem** [FEMessage/el-form-renderer#32]
**Problems
现在有动态设值穿梭框的data需求

**Scene
![image](https://user-images.githubusercontent.com/47966933/57367994-ad7dbd80-71bc-11e9-8e51-bf58e80a9cfa.png)

** Describe
框一中的数据是通过接口请求回来的，期望的是接口请求之前可以动态设值穿梭框

**Comment by 2nthony** [comment]
re #23

**Comment by donaldshen** [comment]
现在 remote 和直接改 content 都可以解决此问题
