### ISSUE TITLE
select可新增模式下multiple为false时会有一个value为undefined的下拉选项

### ISSUE THREAD

**Issue by chenEdgar** [FEMessage/el-form-renderer#33]
**Describe the bug**
见图

**Screenshots**
![image](https://user-images.githubusercontent.com/12596622/57391794-c94f8680-71f1-11e9-8efb-a720e4c8a26a.png)

**To Reproduce**

**Expected behavior**
参看element的select相同功能实现
https://codepen.io/anon/pen/gJaGdx?&editable=true

**Comment by chenEdgar** [comment]
在使用时设置$default值为空字符''能解决问题

**Comment by 2nthony** [comment]
只要`select`没有指定一个默认值:any,并且`allow-create`为`true`时都会有这样的情况

fork&修改了一下提供的codepen
https://codepen.io/evillt/pen/BeoXKX

**Comment by chenEdgar** [comment]
@evillt 准确说是`select`的value是`undefined`或者boolean值，且`allow-create` 为`true`会存在这个情况。

**Comment by 2nthony** [comment]
问题:图片介绍很详细

解决方案: 通过`$default`设置一个值,这个值的类型应该与`$options.value`保持一致

e.g.

```js
$default: '', // 空 string
$options: [
  {
    value: 'hello' // string
  }
]
```
