### ISSUE TITLE
Not allowing to add space and word at the end of textbox and textarea

### ISSUE THREAD

**Issue by GateCorner** [FEMessage/el-form-renderer#40]
I am currently playing with demo page of [url](https://femessage.github.io/el-form-renderer/#/Demo?id=basic)

i entered firstname in textbox then right after that trying to write space and then lastname.

but it won't allow me to add space and lastname at the end. it will trim the space and reset the cursor.

here is the event called while writing the text
![events whilte typing](https://user-images.githubusercontent.com/16802451/59114784-9372fe80-8965-11e9-9dee-d58bc3b75010.png)

updateValue $emit by <RenderFormItem>

please can anyone help to solve this issue.

**Comment by levy9527** [comment]
well，trim is the default setting，you can set trim false。you can find more detail in api doc

**Comment by GateCorner** [comment]
@levy9527  Thank you, its working now.
