### ISSUE TITLE
一个微小的检验触发优化

### ISSUE THREAD

**Issue by quixote1304629** [FEMessage/el-form-renderer#84]
**Is your feature request related to a problem? Please describe.**
![first-tesee-1](https://user-images.githubusercontent.com/32378929/62109142-44e73e00-b2de-11e9-83cd-e5d73fbb1aa9.gif)

场景: 一个表单新增页面、一个save按钮(save第一步是执行表单的validate方法)

步骤:
1.在el-from-renderer中使用 el-cascader[官方]级联选择组件、upload-to-ali组件。
2.页面初次渲染后，直接点击save按钮，此时表单的validate方法执行，各个组件的校验error提示出现。
3.在el-cascader中选中到数据，el-cascader的校验提示不消失；在upload-to-ali选择中图片，其校验提示也不消失。
4.使用trigger: change/blur ，都不理想/无效。
5.el-input、el-select好像无此问题。目前不知道还有没有其他element官方组件校验不能即时触发。

**Describe the solution you'd like**
期望: 
在表单中组件(upload-to-ali、el-cascader...)的值变动时，能够使校验提示正常的显隐藏(或者触发校验方法8 ^_^).

**Describe alternatives you've considered**
使用者的不成熟想法:
1.针对el-cascader[官方]级联选择组件，这种校验可能需要在el-form-renderer中进行改进；
2.针对upload-to-ali这种企业/个人封装的组件，建议在v-model的值变动时手动触发el-form-item的校验方法，如下图。这种触发方式有实践过
![image](https://user-images.githubusercontent.com/32378929/62110595-5aaa3280-b2e1-11e9-9d34-11d545595a5a.png)

**Comment by eviIIt** [comment]
期望贴一下 el-form-renderer 的版本

版本号希望来源于文件 `node_modules/@femessage/el-form-renderer/package.json`

**Comment by quixote1304629** [comment]
"@femessage/el-form-renderer": "1.9.0"，
"@femessage/upload-to-ali": "^1.8.1",

**Comment by eviIIt** [comment]
hi, 现在人手不多，当前的计划是 __优先适配移动端的表单组件__ ，

完成升级，对vant也支持后，回过头来处理这个bug。

> 不过好在不影响填充完后的校验

**Comment by Star945** [comment]
遇到同样问题自定义组件可以在值更改时 即
this.$emit('input', obj)
this.$nextTick(() => {
      this.dispatch('ElFormItem', 'el.form.change', obj)
 })
//dispach方法如下---来自网络
dispatch (componentName, eventName, params) { // 使用了elFormItem组件作为父组件，该图片上传组件的v-model绑定的数据更新时，通知elFormItem组件
    let parent = this.$parent || this.$root
    let name = parent.$options.componentName

    while (parent && (!name || name !== componentName)) {
      parent = parent.$parent

      if (parent) {
        name = parent.$options.componentName
      }
    }
    if (parent) {
      parent.$emit.apply(parent, [eventName].concat(params))
    }
  }
这样还会有一个问题即当你的表单执行条件显示操作后
hidden: form => form.xxx!== 1 && form.xxx!== 2
rules的验证就会失效
再vue调试工具----事件栏里
值改变时没有执行validate方法
而当你提交表单时这个错误提示会消失

**Comment by eviIIt** [comment]
Hi,

之前测试了一摞表单组件和组件, 目前发现以下几个表单组件不会清除验证信息:

- El Cascader
- V Editor
- Upload To Ali

或许像楼上所说, 需要针对这些表单组件半手动触发 element 的 `el.form.change`

**Comment by Star945** [comment]
i'll show you the second question

**Comment by Star945** [comment]
### 第二个问题
![GIF](https://user-images.githubusercontent.com/12809770/65217442-a362b880-dae6-11e9-836c-eca1791eb573.gif)
如图,一开始需求的表单项是隐藏的当选择某个值后显示需求表单这个时候去点击提交触发验证,然后再填写值,自动验证表单规则失效,而再次点击提交手动触发表单验证有效验证会通过,在不执行hidden操作的情况下是不会有这种状况的(这个是个自定义组件,已按照上面dispatch半手动触发验证)

**Comment by levy9527** [comment]
大家久等了，现在我们出差回来了，项目的事情也处理得差不多了，这个 issue 安排上了😄

**Comment by quixote1304629** [comment]
这个微小优化变得“粗大”起来了

**Comment by eviIIt** [comment]
> 这个微小优化变得“粗大”起来了

😂

**Comment by levy9527** [comment]
大家好，bug已修复，欢迎使用最新版本😎
