### ISSUE TITLE
field 组件类型为 Boolean , 值为 false 时, inputFormat 不生效

### ISSUE THREAD

**Issue by HydrogenPan19** [FEMessage/el-form-renderer#94]
## Describe the bug
field 类型为 Boolean , 值为 false 时, inputFormat 不生效

比如,  `el-switch`
使用 inputFormat

```js
var value = item.type === GROUP ? updateValue(item.items) : item.inputFormat && item.inputFormat(values) || values[item.id];
```
inputFormat 返回 false 时，还是使用原来的值

## Expected behavior
绑定 inputFormat 返回的值，包括 `false`, `""` 这些

## environment information
 - 1.11.0

**Comment by eviIIt** [comment]
https://element.eleme.cn/#/zh-CN/component/switch#attributes

不知道你是不是需要自定义的真值和假值，

如果是可以参考文档设置 `active-value` 和 `inactive-value`

如果不是可以贴一下代码并且留下你的详细信息

**Comment by HydrogenPan19** [comment]
active-value 和 inactive-value 默认是 Boolean 的

使用场景是这样的
https://codesandbox.io/embed/github/HydrogenPan19/ElFormRenderer-inputFormat-demo/tree/master/

inputFormat 的返回值为 `false` 和 `0` 时，都会被忽略，导致了 value 的值一会是 inputFormat 格式化过，一会是原本的值

现在改用字符串做标记了
activeValue: 'active',
inactiveValue: 'inactive',

**Comment by levy9527** [comment]
你好，已修复后发版本
