### ISSUE TITLE
table的searchForm通过component传自定义组件，希望可以传prop给该自定义组件

### ISSUE THREAD

**Issue by chenkongming** [FEMessage/el-form-renderer#96]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by eviIIt** [comment]
```js
// form-content
{
  component: YourComponent,
  el: {
    name: 'evillt'
  }
}

// YourComponent
props: {
  name: String
}
```

**Comment by levy9527** [comment]
https://femessage.github.io/el-form-renderer/#/Demo/el
